USE [master]
GO

/****** Object:  Database [Emlak]    Script Date: 18.01.2016 19:06:07 ******/
CREATE DATABASE [Emlak]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Emlak', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Emlak.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Emlak_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Emlak_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Emlak] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Emlak].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Emlak] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Emlak] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Emlak] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Emlak] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Emlak] SET ARITHABORT OFF 
GO

ALTER DATABASE [Emlak] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Emlak] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Emlak] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Emlak] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Emlak] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Emlak] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Emlak] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Emlak] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Emlak] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Emlak] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Emlak] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Emlak] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Emlak] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Emlak] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Emlak] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Emlak] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Emlak] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Emlak] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Emlak] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Emlak] SET  MULTI_USER 
GO

ALTER DATABASE [Emlak] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Emlak] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Emlak] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Emlak] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Emlak] SET  READ_WRITE 
GO


