//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmlakEntities17 : DbContext
    {
        public EmlakEntities17()
            : base("name=EmlakEntities17")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminEkranı> AdminEkranı { get; set; }
        public DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public DbSet<Mesaj> Mesaj { get; set; }
        public DbSet<OnayBekleyen> OnayBekleyen { get; set; }
        public DbSet<Reddedilen> Reddedilen { get; set; }
    }
}
