//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StajProje3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reddedilen
    {
        public int ID { get; set; }
        public string IlanBasligi { get; set; }
        public string KonutTipi { get; set; }
        public string KonutSekli { get; set; }
        public int BinaYasi { get; set; }
        public int OdaSayisi { get; set; }
        public int mKare { get; set; }
        public string Resim { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Semt { get; set; }
        public int Fiyat { get; set; }
        public string Aciklama { get; set; }
        public string Kullanici { get; set; }
        public string Rednedeni { get; set; }
    }
}
